/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NewTaskRouteImport } from './routes/new-task'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiSelectionRouteImport } from './routes/api/selection'
import { Route as TasksIdIndexRouteImport } from './routes/tasks.$id.index'
import { Route as TasksIdEditRouteImport } from './routes/tasks.$id.edit'
import { Route as ApiTasksSuggestEmojisRouteImport } from './routes/api/tasks.suggest-emojis'
import { Route as ApiTasksSnoozeManyRouteImport } from './routes/api/tasks.snooze-many'
import { Route as ApiTasksIdRouteImport } from './routes/api/tasks.$id'
import { Route as ApiProgressTodayRouteImport } from './routes/api/progress.today'
import { Route as ApiLockscreenTimerRouteImport } from './routes/api/lockscreen.timer'
import { Route as ApiLockscreenPushTokenRouteImport } from './routes/api/lockscreen.push-token'
import { Route as ApiLockscreenDeviceRouteImport } from './routes/api/lockscreen.device'
import { Route as ApiHistoryDateRouteImport } from './routes/api/history.$date'
import { Route as ApiAdminBackfillEmojisRouteImport } from './routes/api/admin/backfill-emojis'
import { Route as ApiTasksIdUnsnoozeRouteImport } from './routes/api/tasks.$id.unsnooze'
import { Route as ApiTasksIdTimerRouteImport } from './routes/api/tasks.$id.timer'
import { Route as ApiTasksIdSnoozeRouteImport } from './routes/api/tasks.$id.snooze'
import { Route as ApiTasksIdCompleteRouteImport } from './routes/api/tasks.$id.complete'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewTaskRoute = NewTaskRouteImport.update({
  id: '/new-task',
  path: '/new-task',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSelectionRoute = ApiSelectionRouteImport.update({
  id: '/api/selection',
  path: '/api/selection',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdIndexRoute = TasksIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksIdRoute,
} as any)
const TasksIdEditRoute = TasksIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TasksIdRoute,
} as any)
const ApiTasksSuggestEmojisRoute = ApiTasksSuggestEmojisRouteImport.update({
  id: '/suggest-emojis',
  path: '/suggest-emojis',
  getParentRoute: () => ApiTasksRoute,
} as any)
const ApiTasksSnoozeManyRoute = ApiTasksSnoozeManyRouteImport.update({
  id: '/snooze-many',
  path: '/snooze-many',
  getParentRoute: () => ApiTasksRoute,
} as any)
const ApiTasksIdRoute = ApiTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTasksRoute,
} as any)
const ApiProgressTodayRoute = ApiProgressTodayRouteImport.update({
  id: '/api/progress/today',
  path: '/api/progress/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLockscreenTimerRoute = ApiLockscreenTimerRouteImport.update({
  id: '/api/lockscreen/timer',
  path: '/api/lockscreen/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLockscreenPushTokenRoute = ApiLockscreenPushTokenRouteImport.update({
  id: '/api/lockscreen/push-token',
  path: '/api/lockscreen/push-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLockscreenDeviceRoute = ApiLockscreenDeviceRouteImport.update({
  id: '/api/lockscreen/device',
  path: '/api/lockscreen/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryDateRoute = ApiHistoryDateRouteImport.update({
  id: '/api/history/$date',
  path: '/api/history/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBackfillEmojisRoute = ApiAdminBackfillEmojisRouteImport.update({
  id: '/api/admin/backfill-emojis',
  path: '/api/admin/backfill-emojis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIdUnsnoozeRoute = ApiTasksIdUnsnoozeRouteImport.update({
  id: '/unsnooze',
  path: '/unsnooze',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiTasksIdTimerRoute = ApiTasksIdTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiTasksIdSnoozeRoute = ApiTasksIdSnoozeRouteImport.update({
  id: '/snooze',
  path: '/snooze',
  getParentRoute: () => ApiTasksIdRoute,
} as any)
const ApiTasksIdCompleteRoute = ApiTasksIdCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => ApiTasksIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/new-task': typeof NewTaskRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/api/selection': typeof ApiSelectionRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/tasks/': typeof TasksIndexRoute
  '/api/admin/backfill-emojis': typeof ApiAdminBackfillEmojisRoute
  '/api/history/$date': typeof ApiHistoryDateRoute
  '/api/lockscreen/device': typeof ApiLockscreenDeviceRoute
  '/api/lockscreen/push-token': typeof ApiLockscreenPushTokenRoute
  '/api/lockscreen/timer': typeof ApiLockscreenTimerRoute
  '/api/progress/today': typeof ApiProgressTodayRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/api/tasks/snooze-many': typeof ApiTasksSnoozeManyRoute
  '/api/tasks/suggest-emojis': typeof ApiTasksSuggestEmojisRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
  '/tasks/$id/': typeof TasksIdIndexRoute
  '/api/tasks/$id/complete': typeof ApiTasksIdCompleteRoute
  '/api/tasks/$id/snooze': typeof ApiTasksIdSnoozeRoute
  '/api/tasks/$id/timer': typeof ApiTasksIdTimerRoute
  '/api/tasks/$id/unsnooze': typeof ApiTasksIdUnsnoozeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/new-task': typeof NewTaskRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/api/selection': typeof ApiSelectionRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/tasks': typeof TasksIndexRoute
  '/api/admin/backfill-emojis': typeof ApiAdminBackfillEmojisRoute
  '/api/history/$date': typeof ApiHistoryDateRoute
  '/api/lockscreen/device': typeof ApiLockscreenDeviceRoute
  '/api/lockscreen/push-token': typeof ApiLockscreenPushTokenRoute
  '/api/lockscreen/timer': typeof ApiLockscreenTimerRoute
  '/api/progress/today': typeof ApiProgressTodayRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/api/tasks/snooze-many': typeof ApiTasksSnoozeManyRoute
  '/api/tasks/suggest-emojis': typeof ApiTasksSuggestEmojisRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
  '/tasks/$id': typeof TasksIdIndexRoute
  '/api/tasks/$id/complete': typeof ApiTasksIdCompleteRoute
  '/api/tasks/$id/snooze': typeof ApiTasksIdSnoozeRoute
  '/api/tasks/$id/timer': typeof ApiTasksIdTimerRoute
  '/api/tasks/$id/unsnooze': typeof ApiTasksIdUnsnoozeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/new-task': typeof NewTaskRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/api/selection': typeof ApiSelectionRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/tasks/$id': typeof TasksIdRouteWithChildren
  '/tasks/': typeof TasksIndexRoute
  '/api/admin/backfill-emojis': typeof ApiAdminBackfillEmojisRoute
  '/api/history/$date': typeof ApiHistoryDateRoute
  '/api/lockscreen/device': typeof ApiLockscreenDeviceRoute
  '/api/lockscreen/push-token': typeof ApiLockscreenPushTokenRoute
  '/api/lockscreen/timer': typeof ApiLockscreenTimerRoute
  '/api/progress/today': typeof ApiProgressTodayRoute
  '/api/tasks/$id': typeof ApiTasksIdRouteWithChildren
  '/api/tasks/snooze-many': typeof ApiTasksSnoozeManyRoute
  '/api/tasks/suggest-emojis': typeof ApiTasksSuggestEmojisRoute
  '/tasks/$id/edit': typeof TasksIdEditRoute
  '/tasks/$id/': typeof TasksIdIndexRoute
  '/api/tasks/$id/complete': typeof ApiTasksIdCompleteRoute
  '/api/tasks/$id/snooze': typeof ApiTasksIdSnoozeRoute
  '/api/tasks/$id/timer': typeof ApiTasksIdTimerRoute
  '/api/tasks/$id/unsnooze': typeof ApiTasksIdUnsnoozeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/new-task'
    | '/settings'
    | '/stats'
    | '/api/selection'
    | '/api/stats'
    | '/api/tasks'
    | '/tasks/$id'
    | '/tasks/'
    | '/api/admin/backfill-emojis'
    | '/api/history/$date'
    | '/api/lockscreen/device'
    | '/api/lockscreen/push-token'
    | '/api/lockscreen/timer'
    | '/api/progress/today'
    | '/api/tasks/$id'
    | '/api/tasks/snooze-many'
    | '/api/tasks/suggest-emojis'
    | '/tasks/$id/edit'
    | '/tasks/$id/'
    | '/api/tasks/$id/complete'
    | '/api/tasks/$id/snooze'
    | '/api/tasks/$id/timer'
    | '/api/tasks/$id/unsnooze'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/new-task'
    | '/settings'
    | '/stats'
    | '/api/selection'
    | '/api/stats'
    | '/api/tasks'
    | '/tasks'
    | '/api/admin/backfill-emojis'
    | '/api/history/$date'
    | '/api/lockscreen/device'
    | '/api/lockscreen/push-token'
    | '/api/lockscreen/timer'
    | '/api/progress/today'
    | '/api/tasks/$id'
    | '/api/tasks/snooze-many'
    | '/api/tasks/suggest-emojis'
    | '/tasks/$id/edit'
    | '/tasks/$id'
    | '/api/tasks/$id/complete'
    | '/api/tasks/$id/snooze'
    | '/api/tasks/$id/timer'
    | '/api/tasks/$id/unsnooze'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/new-task'
    | '/settings'
    | '/stats'
    | '/api/selection'
    | '/api/stats'
    | '/api/tasks'
    | '/tasks/$id'
    | '/tasks/'
    | '/api/admin/backfill-emojis'
    | '/api/history/$date'
    | '/api/lockscreen/device'
    | '/api/lockscreen/push-token'
    | '/api/lockscreen/timer'
    | '/api/progress/today'
    | '/api/tasks/$id'
    | '/api/tasks/snooze-many'
    | '/api/tasks/suggest-emojis'
    | '/tasks/$id/edit'
    | '/tasks/$id/'
    | '/api/tasks/$id/complete'
    | '/api/tasks/$id/snooze'
    | '/api/tasks/$id/timer'
    | '/api/tasks/$id/unsnooze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  NewTaskRoute: typeof NewTaskRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  ApiSelectionRoute: typeof ApiSelectionRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiTasksRoute: typeof ApiTasksRouteWithChildren
  TasksIdRoute: typeof TasksIdRouteWithChildren
  TasksIndexRoute: typeof TasksIndexRoute
  ApiAdminBackfillEmojisRoute: typeof ApiAdminBackfillEmojisRoute
  ApiHistoryDateRoute: typeof ApiHistoryDateRoute
  ApiLockscreenDeviceRoute: typeof ApiLockscreenDeviceRoute
  ApiLockscreenPushTokenRoute: typeof ApiLockscreenPushTokenRoute
  ApiLockscreenTimerRoute: typeof ApiLockscreenTimerRoute
  ApiProgressTodayRoute: typeof ApiProgressTodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-task': {
      id: '/new-task'
      path: '/new-task'
      fullPath: '/new-task'
      preLoaderRoute: typeof NewTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/selection': {
      id: '/api/selection'
      path: '/api/selection'
      fullPath: '/api/selection'
      preLoaderRoute: typeof ApiSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id/': {
      id: '/tasks/$id/'
      path: '/'
      fullPath: '/tasks/$id/'
      preLoaderRoute: typeof TasksIdIndexRouteImport
      parentRoute: typeof TasksIdRoute
    }
    '/tasks/$id/edit': {
      id: '/tasks/$id/edit'
      path: '/edit'
      fullPath: '/tasks/$id/edit'
      preLoaderRoute: typeof TasksIdEditRouteImport
      parentRoute: typeof TasksIdRoute
    }
    '/api/tasks/suggest-emojis': {
      id: '/api/tasks/suggest-emojis'
      path: '/suggest-emojis'
      fullPath: '/api/tasks/suggest-emojis'
      preLoaderRoute: typeof ApiTasksSuggestEmojisRouteImport
      parentRoute: typeof ApiTasksRoute
    }
    '/api/tasks/snooze-many': {
      id: '/api/tasks/snooze-many'
      path: '/snooze-many'
      fullPath: '/api/tasks/snooze-many'
      preLoaderRoute: typeof ApiTasksSnoozeManyRouteImport
      parentRoute: typeof ApiTasksRoute
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteImport
      parentRoute: typeof ApiTasksRoute
    }
    '/api/progress/today': {
      id: '/api/progress/today'
      path: '/api/progress/today'
      fullPath: '/api/progress/today'
      preLoaderRoute: typeof ApiProgressTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lockscreen/timer': {
      id: '/api/lockscreen/timer'
      path: '/api/lockscreen/timer'
      fullPath: '/api/lockscreen/timer'
      preLoaderRoute: typeof ApiLockscreenTimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lockscreen/push-token': {
      id: '/api/lockscreen/push-token'
      path: '/api/lockscreen/push-token'
      fullPath: '/api/lockscreen/push-token'
      preLoaderRoute: typeof ApiLockscreenPushTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lockscreen/device': {
      id: '/api/lockscreen/device'
      path: '/api/lockscreen/device'
      fullPath: '/api/lockscreen/device'
      preLoaderRoute: typeof ApiLockscreenDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history/$date': {
      id: '/api/history/$date'
      path: '/api/history/$date'
      fullPath: '/api/history/$date'
      preLoaderRoute: typeof ApiHistoryDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/backfill-emojis': {
      id: '/api/admin/backfill-emojis'
      path: '/api/admin/backfill-emojis'
      fullPath: '/api/admin/backfill-emojis'
      preLoaderRoute: typeof ApiAdminBackfillEmojisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$id/unsnooze': {
      id: '/api/tasks/$id/unsnooze'
      path: '/unsnooze'
      fullPath: '/api/tasks/$id/unsnooze'
      preLoaderRoute: typeof ApiTasksIdUnsnoozeRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/tasks/$id/timer': {
      id: '/api/tasks/$id/timer'
      path: '/timer'
      fullPath: '/api/tasks/$id/timer'
      preLoaderRoute: typeof ApiTasksIdTimerRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/tasks/$id/snooze': {
      id: '/api/tasks/$id/snooze'
      path: '/snooze'
      fullPath: '/api/tasks/$id/snooze'
      preLoaderRoute: typeof ApiTasksIdSnoozeRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
    '/api/tasks/$id/complete': {
      id: '/api/tasks/$id/complete'
      path: '/complete'
      fullPath: '/api/tasks/$id/complete'
      preLoaderRoute: typeof ApiTasksIdCompleteRouteImport
      parentRoute: typeof ApiTasksIdRoute
    }
  }
}

interface ApiTasksIdRouteChildren {
  ApiTasksIdCompleteRoute: typeof ApiTasksIdCompleteRoute
  ApiTasksIdSnoozeRoute: typeof ApiTasksIdSnoozeRoute
  ApiTasksIdTimerRoute: typeof ApiTasksIdTimerRoute
  ApiTasksIdUnsnoozeRoute: typeof ApiTasksIdUnsnoozeRoute
}

const ApiTasksIdRouteChildren: ApiTasksIdRouteChildren = {
  ApiTasksIdCompleteRoute: ApiTasksIdCompleteRoute,
  ApiTasksIdSnoozeRoute: ApiTasksIdSnoozeRoute,
  ApiTasksIdTimerRoute: ApiTasksIdTimerRoute,
  ApiTasksIdUnsnoozeRoute: ApiTasksIdUnsnoozeRoute,
}

const ApiTasksIdRouteWithChildren = ApiTasksIdRoute._addFileChildren(
  ApiTasksIdRouteChildren,
)

interface ApiTasksRouteChildren {
  ApiTasksIdRoute: typeof ApiTasksIdRouteWithChildren
  ApiTasksSnoozeManyRoute: typeof ApiTasksSnoozeManyRoute
  ApiTasksSuggestEmojisRoute: typeof ApiTasksSuggestEmojisRoute
}

const ApiTasksRouteChildren: ApiTasksRouteChildren = {
  ApiTasksIdRoute: ApiTasksIdRouteWithChildren,
  ApiTasksSnoozeManyRoute: ApiTasksSnoozeManyRoute,
  ApiTasksSuggestEmojisRoute: ApiTasksSuggestEmojisRoute,
}

const ApiTasksRouteWithChildren = ApiTasksRoute._addFileChildren(
  ApiTasksRouteChildren,
)

interface TasksIdRouteChildren {
  TasksIdEditRoute: typeof TasksIdEditRoute
  TasksIdIndexRoute: typeof TasksIdIndexRoute
}

const TasksIdRouteChildren: TasksIdRouteChildren = {
  TasksIdEditRoute: TasksIdEditRoute,
  TasksIdIndexRoute: TasksIdIndexRoute,
}

const TasksIdRouteWithChildren =
  TasksIdRoute._addFileChildren(TasksIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  NewTaskRoute: NewTaskRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  ApiSelectionRoute: ApiSelectionRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiTasksRoute: ApiTasksRouteWithChildren,
  TasksIdRoute: TasksIdRouteWithChildren,
  TasksIndexRoute: TasksIndexRoute,
  ApiAdminBackfillEmojisRoute: ApiAdminBackfillEmojisRoute,
  ApiHistoryDateRoute: ApiHistoryDateRoute,
  ApiLockscreenDeviceRoute: ApiLockscreenDeviceRoute,
  ApiLockscreenPushTokenRoute: ApiLockscreenPushTokenRoute,
  ApiLockscreenTimerRoute: ApiLockscreenTimerRoute,
  ApiProgressTodayRoute: ApiProgressTodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
